
language: scala
sudo: false

scala:
  - 2.12.3
jdk:
  - oraclejdk8

env:
  global:
    - MAIN_SCALA_VERSION=2.12.3

services:
  - docker

script:
  - project/travis-build.sh
after_success:
  - project/travis-post-build.sh

cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete